import pandas as pd
# ^^^ pyforest auto-imports - don't write above this line
# Importing convetion

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
!pip3 install pandas --upgrade 

In [ ]:
pd.__version__

# What is Pandas?

Pandas can be thought as an enhanced version of numpy arrays. In this case, the rows and columns can be identified with labels instead of just simple integer indices.

There are **3** main pandas elements we **need** to understand.
1. Pandas Series
2. Pandas DataFrame
3. Index

# The Pandas Series

A pandas series is a one-dimensional (**1-D**) indexed array.

In [5]:
pd

<module 'pandas' from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/__init__.py'>

In [6]:
pd.Series()

<ipython-input-6-fa15c544da3b>:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  pd.Series()


Series([], dtype: float64)

### Series from a list

In [9]:
pd.Series([5,8,3])

0    5
1    8
2    3
dtype: int64

In [10]:
pd.Series([5,8,3])[1]

8

In [11]:
pd.Series(['a','b','c'])

0    a
1    b
2    c
dtype: object

In [13]:
pd.Series(['a','b','c'])[0]

'a'

In [15]:
x = pd.Series(['a', 2, 3])

In [16]:
x

0    a
1    2
2    3
dtype: object

In [19]:
type(x[0])

str

In [20]:
type(x[2])

int

In [21]:
data = pd.Series([10,23,3,43,25,136])

In [22]:
data

0     10
1     23
2      3
3     43
4     25
5    136
dtype: int64

## Values and Indexes

In [24]:
data.index

RangeIndex(start=0, stop=6, step=1)

In [26]:
data.values

array([ 10,  23,   3,  43,  25, 136])

In [28]:
data.max()

136

In [29]:
type(data.index)

pandas.core.indexes.range.RangeIndex

In [30]:
type(data.values)

numpy.ndarray

In [31]:
data

0     10
1     23
2      3
3     43
4     25
5    136
dtype: int64

In [32]:
test = pd.Series(['a','b','c'])

In [35]:
type(test.values)

numpy.ndarray

## Accessing elements 

Can be done like a numpy array

In [36]:
data

0     10
1     23
2      3
3     43
4     25
5    136
dtype: int64

In [37]:
data[0]

10

In [38]:
data[4:]

4     25
5    136
dtype: int64

Em resumo: pandas series pode ser considerado uma numpy array de 1-D

### What is the difference then? Numpy array vs Pandas Series

Mostly the index notation.

Numpy arrays only have the **implicit** index associated with its location. By using a **explicit** index notation, Pandas Series are much more flexible. For example:

## Index don't need to be numbers.

In [62]:
z = pd.Series(data=[1,2,3,5,2,7], index=['Andre','Rai', 'Lucas', 'Matheus','Eveline', 'Yukari'])
z

Andre      1
Rai        2
Lucas      3
Matheus    5
Eveline    2
Yukari     7
dtype: int64

In [44]:
y = pd.Series(data=[1,2,3], index=[8293, 10293,10])

In [46]:
y

8293     1
10293    2
10       3
dtype: int64

In [56]:
y.index

Int64Index([8293, 10293, 10], dtype='int64')

In [54]:
y[y.index[-1]]

3

In [66]:
np.array([1,2,3,5,8])[2:4]

array([3, 5])

In [64]:
z['Rai':'Eveline']

Rai        2
Lucas      3
Matheus    5
Eveline    2
dtype: int64

In [71]:
z.sort_index()

Andre      1
Eveline    2
Lucas      3
Matheus    5
Rai        2
Yukari     7
dtype: int64

In [72]:
x = pd.Series(data=[1,2,3], index=[0,10,2])
x

0     1
10    2
2     3
dtype: int64

In [73]:
x[10]

2

In [74]:
data = pd.Series(data=[1,2,3,4], 
                 index=['ajaiofj','b', 'caksok', 'd'])

In [76]:
data

ajaiofj    1
b          2
caksok     3
d          4
dtype: int64

In [79]:
z = pd.Series(data=[1,2,3,5,2,7], index=['Andre','Andre', 'Lucas', 'Matheus','Eveline', 'Yukari'])
z

Andre      1
Andre      2
Lucas      3
Matheus    5
Eveline    2
Yukari     7
dtype: int64

In [81]:
z['Andre']

Andre    1
Andre    2
dtype: int64

In [83]:
z.keys()

Index(['Andre', 'Andre', 'Lucas', 'Matheus', 'Eveline', 'Yukari'], dtype='object')

In [85]:
z.values

array([1, 2, 3, 5, 2, 7])

In [88]:
list(z.items())

[('Andre', 1),
 ('Andre', 2),
 ('Lucas', 3),
 ('Matheus', 5),
 ('Eveline', 2),
 ('Yukari', 7)]

### Then how can I access this pandas series?

In [89]:
data['ajaiofj']

1

## Index don't need to be in sequence

In [90]:
data = pd.Series(data=[1,2,3,4], 
                 index=[1,7,4313,19])

In [91]:
data

1       1
7       2
4313    3
19      4
dtype: int64

### One can think of a pandas series, then, as a form of dictionary, in which the indexes are keys and the rows are the values

Let's create a pandas series from a dict.

In [92]:
data.keys()

Int64Index([1, 7, 4313, 19], dtype='int64')

In [95]:
my_dict = {'MATHEUS': 0, 
           'ANDRE':10}

In [96]:
my_dict

{'MATHEUS': 0, 'ANDRE': 10}

In [97]:
pd.Series(my_dict)

MATHEUS     0
ANDRE      10
dtype: int64

In [98]:
my_dict = {0: 0, 1:10}
pd.Series(my_dict)

0     0
1    10
dtype: int64

In [99]:
pd.Series(my_dict)[0]

0

# What about > 1-D?


# Pandas DataFrame


Pandas Dataframes can be thought as a generalization of **2-D** numpy arrays. However, again, they bring flexibility on both the indices and column names.

In [100]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [101]:
type(pd.DataFrame())

pandas.core.frame.DataFrame

## Pandas DataFrame can be thought as a group of Pandas Series

In [103]:
my_dict = {'MATHEUS': 0, 
           'ANDRE':10}

data = pd.Series(my_dict)

In [104]:
data

MATHEUS     0
ANDRE      10
dtype: int64

In [105]:
another_dict = {'MATHEUS': -20,'ANDRE': 22}

data_2 = pd.Series(another_dict)

In [106]:
data_2

MATHEUS   -20
ANDRE      22
dtype: int64

# Create dataframe as a collection of Series

In [107]:
{'coluna1':data, 'coluna2':data_2}

{'coluna1': MATHEUS     0
 ANDRE      10
 dtype: int64, 'coluna2': MATHEUS   -20
 ANDRE      22
 dtype: int64}

In [111]:
x = pd.DataFrame({'coluna1':data, 'coluna2':data_2, 'coluna3':data})
x 

coluna1  coluna2  coluna3
MATHEUS        0      -20        0
ANDRE         10       22       10

In [117]:
x['coluna2']

MATHEUS   -20
ANDRE      22
Name: coluna2, dtype: int64

In [116]:
x[['coluna1','coluna3']]

coluna1  coluna3
MATHEUS        0        0
ANDRE         10       10

In [119]:
x['coluna1']

MATHEUS     0
ANDRE      10
Name: coluna1, dtype: int64

In [118]:
x[['coluna1']]

coluna1
MATHEUS        0
ANDRE         10

In [120]:
x['coluna1']

MATHEUS     0
ANDRE      10
Name: coluna1, dtype: int64

In [121]:
pd.DataFrame(x['coluna1'])

coluna1
MATHEUS        0
ANDRE         10

## So a dataframe can be thought of as a dictionary, in which keys are the column names and values are the pandas series themselves

In [132]:
a = np.random.random((3,5))

In [133]:
a

array([[0.80421392, 0.99674553, 0.62059202, 0.51001389, 0.92111311],
       [0.45909029, 0.47839874, 0.37627582, 0.78402994, 0.77838774],
       [0.73753159, 0.94333342, 0.40495579, 0.03770107, 0.47058669]])

In [134]:
a = pd.DataFrame(a, columns=['a','b','c','d','e'])
a

a         b         c         d         e
0  0.804214  0.996746  0.620592  0.510014  0.921113
1  0.459090  0.478399  0.376276  0.784030  0.778388
2  0.737532  0.943333  0.404956  0.037701  0.470587

## From a list in 1-D

In [125]:
pd.DataFrame(data=[1,2,3], columns=['ironhack'], index=['a','b','c'])

ironhack
a         1
b         2
c         3

## From a list in > 1-D (let's remember numpy arrays here!)

In [135]:
np.array([[1,2,3],[-5,-6,-7]]).shape

(2, 3)

In [141]:
df = pd.DataFrame(data=[[1,2,3],[-5,-6,-7]], columns=['ironhack','digital_house','lewagon'])
df

ironhack  digital_house  lewagon
0         1              2        3
1        -5             -6       -7

In [142]:
df.shape

(2, 3)

### Column names and indexes

In [143]:
df

ironhack  digital_house  lewagon
0         1              2        3
1        -5             -6       -7

In [144]:
df['digital_house']

0    2
1   -6
Name: digital_house, dtype: int64

In [145]:
type(df['digital_house'])

pandas.core.series.Series

In [146]:
df[['digital_house','lewagon']]

digital_house  lewagon
0              2        3
1             -6       -7

In [147]:
df[['ironhack']]

ironhack
0         1
1        -5

# Creating dataframes

In [148]:
# what if I dont specify any column name?
pd.DataFrame(data=[[1,2,3,4],[3,4,6,7]])

0  1  2  3
0  1  2  3  4
1  3  4  6  7

## From a dictionary

In [149]:
df = pd.DataFrame({'ironhack':[1,3,5,6,3,2], 'digital': [1,3,2,4,3,1]} )

In [153]:
df.head(1)

ironhack  digital
0         1        1

In [154]:
df.tail(2)

ironhack  digital
4         3        3
5         2        1

In [ ]:
df[['ironhack']]

## From a dictionary composed by pandas Series

In [155]:
serie_1 = pd.Series([1,2,3])
serie_2 = pd.Series([3,4,6])

pd.DataFrame({'a': serie_1, 'b':serie_2})
#serie_2

a  b
0  1  3
1  2  4
2  3  6

In [158]:
x = pd.DataFrame({'CPF': [1,35,67,3], 'vlr':[1,3,4,6]})

In [165]:
x.values

array([[ 1,  1],
       [35,  3],
       [67,  4],
       [ 3,  6]])

In [168]:
x

CPF  vlr
0    1    1
1   35    3
2   67    4
3    3    6

In [169]:
x.sum()

CPF    106
vlr     14
dtype: int64

In [170]:
x.sum(axis=0)

CPF    106
vlr     14
dtype: int64

In [172]:
x = pd.DataFrame({'CPF': [1,35,67,3], 'vlr_cheque':[1,3,4,6], 'vlr_cartao':[30, 2,5,10]})
x

CPF  vlr_cheque  vlr_cartao
0    1           1          30
1   35           3           2
2   67           4           5
3    3           6          10

In [175]:
x[['vlr_cheque', 'vlr_cartao']]

vlr_cheque  vlr_cartao
0           1          30
1           3           2
2           4           5
3           6          10

In [179]:
x

CPF  vlr_cheque  vlr_cartao
0    1           1          30
1   35           3           2
2   67           4           5
3    3           6          10

In [178]:
x.sum(axis=1)

0    32
1    40
2    76
3    19
dtype: int64

In [176]:
x[['vlr_cheque', 'vlr_cartao']].sum(axis=1)

0    31
1     5
2     9
3    16
dtype: int64

In [180]:
x['soma_vlr'] = x[['vlr_cheque', 'vlr_cartao']].sum(axis=1)

In [181]:
x

CPF  vlr_cheque  vlr_cartao  soma_vlr
0    1           1          30        31
1   35           3           2         5
2   67           4           5         9
3    3           6          10        16

In [182]:
x['random'] = 6
x

CPF  vlr_cheque  vlr_cartao  soma_vlr  random
0    1           1          30        31       6
1   35           3           2         5       6
2   67           4           5         9       6
3    3           6          10        16       6

In [185]:
x['soma_diferente_vlr'] = x['vlr_cheque'] + x['vlr_cartao']
x

CPF  vlr_cheque  vlr_cartao  soma_vlr  random  soma_diferente_vlr
0    1           1          30        31       6                  31
1   35           3           2         5       6                   5
2   67           4           5         9       6                   9
3    3           6          10        16       6                  16

In [187]:
x['vlr_cheque'] + x['vlr_cartao']

0    31
1     5
2     9
3    16
dtype: int64

## Test

In [190]:
xx = pd.Series([1,1,1,1],)
yy = pd.Series([2,2,2,2], index=['a','b', 'c','d'])
yy

a    2
b    2
c    2
d    2
dtype: int64

In [191]:
xx + yy

0   NaN
1   NaN
2   NaN
3   NaN
a   NaN
b   NaN
c   NaN
d   NaN
dtype: float64

In [192]:
xx = pd.Series([1,1,1,1],)
yy = pd.Series([2,2,2,2], index=[2,3,4,5])
yy

2    2
3    2
4    2
5    2
dtype: int64

In [193]:
xx + yy

0    NaN
1    NaN
2    3.0
3    3.0
4    NaN
5    NaN
dtype: float64

## From a dictionary composed by lists

In [195]:
pd.DataFrame({'ironhack_students': ['a','b','c'],
              'bla':[10, 10, 0]})

ironhack_students  bla
0                 a   10
1                 b   10
2                 c    0

## From a numpy array

In [198]:
a = np.random.random(size=(5, 3))
a

array([[0.32799523, 0.09982238, 0.41522353],
       [0.81434018, 0.80024322, 0.6051318 ],
       [0.17627968, 0.71904549, 0.79381741],
       [0.00696024, 0.13066971, 0.07158705],
       [0.42431148, 0.45711173, 0.03200865]])

In [201]:
pd.DataFrame(a)[[0,2]]

0         2
0  0.327995  0.415224
1  0.814340  0.605132
2  0.176280  0.793817
3  0.006960  0.071587
4  0.424311  0.032009

In [202]:
pd.DataFrame(a, columns=['a', 'b', 'c'])

a         b         c
0  0.327995  0.099822  0.415224
1  0.814340  0.800243  0.605132
2  0.176280  0.719045  0.793817
3  0.006960  0.130670  0.071587
4  0.424311  0.457112  0.032009

In [203]:
x = pd.DataFrame([pd.Series([1,2],index=['Matheus','Andre']), pd.Series([4,7], index=['Matheus', 'Andre'])])

## Math operations

In [204]:
x

Matheus  Andre
0        1      2
1        4      7

In [205]:
x.transpose()

0  1
Matheus  1  4
Andre    2  7

In [206]:
x.T

0  1
Matheus  1  4
Andre    2  7

In [207]:
x.mean()

Matheus    2.5
Andre      4.5
dtype: float64

In [208]:
x.mean(axis=1)

0    1.5
1    5.5
dtype: float64

In [209]:
x.std()

Matheus    2.121320
Andre      3.535534
dtype: float64

In [210]:
x.describe()

Matheus     Andre
count  2.00000  2.000000
mean   2.50000  4.500000
std    2.12132  3.535534
min    1.00000  2.000000
25%    1.75000  3.250000
50%    2.50000  4.500000
75%    3.25000  5.750000
max    4.00000  7.000000

In [211]:
x['Andre']

0    2
1    7
Name: Andre, dtype: int64

In [212]:
x.Andre

0    2
1    7
Name: Andre, dtype: int64

# Acessing methods

In [216]:
x = pd.DataFrame(np.random.random((10, 3)), columns=['a', 'b', 'c'])
x


a         b         c
0  0.603989  0.549502  0.086998
1  0.485692  0.206355  0.022385
2  0.588083  0.004855  0.538379
3  0.711403  0.201622  0.421743
4  0.999073  0.003914  0.308491
5  0.433816  0.099225  0.448726
6  0.753335  0.151764  0.369651
7  0.773552  0.755691  0.263804
8  0.909985  0.260152  0.087395
9  0.932064  0.153422  0.549986

## iloc


In [217]:
x.iloc[4,2]

0.30849133652264416

In [220]:
y = x.iloc[4:,:]
y

a         b         c
4  0.999073  0.003914  0.308491
5  0.433816  0.099225  0.448726
6  0.753335  0.151764  0.369651
7  0.773552  0.755691  0.263804
8  0.909985  0.260152  0.087395
9  0.932064  0.153422  0.549986

In [221]:
y.iloc[0,:]

a    0.999073
b    0.003914
c    0.308491
Name: 4, dtype: float64

## loc

In [218]:
x.loc[4, 'c']

0.30849133652264416

In [222]:
y.loc[0, 'c']

KeyError: 0

# Pandas Index

In [223]:
pd.Index([1,2,3])

Int64Index([1, 2, 3], dtype='int64')

In [224]:
data.index

Index(['MATHEUS', 'ANDRE'], dtype='object')

In [225]:
data.index.values

array(['MATHEUS', 'ANDRE'], dtype=object)

In [226]:
pd.DataFrame([item for item in range(10)], index=[np.random.randint(0, 1000) for item in range(10)], columns=['colname']).query('colname > 2 and colname < 6')

colname
896        3
566        4
367        5

# Drugs

https://github.com/satwikkansal/wtfpython

In [227]:
a = 256
b = 256

In [228]:
a == b

True

In [229]:
a is b

True

In [230]:
a = 258
b = 258

In [231]:
a == b

True

In [232]:
a is b

False

In [233]:
a = 'python'
b = 'python'

In [234]:
a == b

True

In [235]:
a is b

True

In [236]:
a = 'python 3'
b = 'python 3'

In [237]:
a is b

False